name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: win
        - name: macOS
          os: macos-latest
          target: mac
        - name: Android32
          os: ubuntu-latest
          target: android32
        - name: Android64
          os: ubuntu-latest
          target: android64

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Compila la mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
          build-config: Release